// Content for the service landing pages (one page per keyword group).
// Each page renders through components/ServicePage.js at /<slug>.

export const SERVICE_PAGES = [
  {
    slug: "google-ads-agency",
    navLabel: "Google Ads",
    metaTitle: "Google Ads Agency — Expert Google Ads Management & PPC",
    metaDescription:
      "Looking for the best Google Ads agency? MindandMatrix Co. manages Search, Performance Max, YouTube and Shopping campaigns built around revenue and booked leads — for brands and as a white label partner for agencies.",
    keywords: ["Google Ads agency", "best Google Ads agency", "top Google Ads agency", "Google Ads management", "PPC agency"],
    serviceType: "Google Ads management",
    eyebrow: "Google Ads agency",
    h1: ["The Google Ads agency measured on ", "revenue, not clicks."],
    lead:
      "We plan, build and optimize Google Search, Performance Max, YouTube, Display and Shopping campaigns that bring in bookings, leads and sales. Hire us directly, or resell our Google Ads management under your own agency brand.",
    checks: [
      "Search, Performance Max, YouTube, Display & Shopping",
      "Conversion tracking set up before we spend a dollar",
      "Weekly optimization and clear monthly reporting",
    ],
    formTitle: "Get a free Google Ads audit",
    whyTitle: "What makes a top Google Ads agency",
    whyIntro:
      "Most Google Ads accounts waste budget on broad keywords, weak landing pages and broken tracking. The best Google Ads agencies fix the foundations first, then scale what is proven to convert.",
    why: [
      ["Intent-led keyword strategy", "We research the searches your buyers actually make, group them by intent and block irrelevant traffic with aggressive negative keyword lists."],
      ["Tight campaign structure", "Campaigns are split by service, location and intent so every ad matches the search and Quality Score stays high — which lowers your cost per click."],
      ["Performance Max done properly", "Asset groups, audience signals and feed optimization so Google’s AI spends on buyers, not on cheap placements."],
      ["Ads and landing pages together", "We write and test ad copy, extensions and landing pages as one funnel, because a click is only as good as the page it lands on."],
      ["Accurate conversion data", "GA4, Google Tag Manager, enhanced conversions and offline conversion imports, so Smart Bidding learns from real leads and sales."],
      ["Budget control", "Dayparting, location bid adjustments and Target CPA / ROAS bidding once the data supports it. No wasted impressions."],
    ],
    includedTitle: "Google Ads management services",
    included: [
      "Account audit and competitor research",
      "Keyword research and negative keyword lists",
      "Search, Performance Max, YouTube, Display and Shopping campaigns",
      "Responsive search ads, extensions and creative testing",
      "Landing page recommendations or full page builds",
      "GA4, Google Tag Manager and enhanced conversions",
      "Merchant Center and product feed optimization",
      "Weekly optimization and monthly performance reports",
    ],
    steps: [
      ["Free audit", "We review your account, tracking and landing pages and show you exactly where budget is being wasted."],
      ["Tracking & build", "We fix conversion tracking, then restructure or build campaigns around your highest-value searches."],
      ["Optimize & scale", "Weekly bid, keyword and creative optimization. We scale budgets only when the numbers prove it."],
    ],
    faqs: [
      ["How do I choose the best Google Ads agency?", "Look for an agency that sets up accurate conversion tracking first, reports on leads, sales and ROAS rather than clicks, shows real case studies, and gives you full ownership of your ad account. That is how we work."],
      ["How much should I spend on Google Ads?", "It depends on your market and cost per click. Many local service businesses start between $1,000 and $5,000 a month in ad spend. We’ll recommend a starting budget after the free audit."],
      ["How long until Google Ads shows results?", "Search campaigns usually bring leads in the first week. Smart Bidding and Performance Max typically need 2–6 weeks of conversion data to stabilize and improve."],
      ["Do you work with agencies as a white label Google Ads partner?", "Yes. We manage Google Ads for agencies under their brand, with branded reports and an NDA. Your clients only ever see your agency."],
      ["Who owns the Google Ads account?", "You do. We work through manager (MCC) access and you can remove us at any time."],
    ],
  },
  {
    slug: "facebook-ads-agency",
    navLabel: "Facebook & Instagram Ads",
    metaTitle: "Facebook Ads Agency — Facebook & Instagram Ads Management",
    metaDescription:
      "Searching for the best Facebook ads agency? We run Facebook and Instagram (Meta) ad campaigns with scroll-stopping creatives, Conversions API tracking and full-funnel retargeting — for brands and white label for agencies.",
    keywords: ["Facebook ads agency", "best Facebook ads agency", "top Facebook ads agency", "Meta ads agency", "Instagram ads agency"],
    serviceType: "Facebook and Instagram advertising",
    eyebrow: "Facebook & Instagram ads agency",
    h1: ["Facebook & Instagram ads that turn ", "scrolls into customers."],
    lead:
      "We plan Meta ad campaigns, make the creatives and UGC, set up the Pixel and Conversions API, and optimize daily for leads and sales. Work with us directly or white label our Facebook ads management for your agency’s clients.",
    checks: [
      "Lead generation, e-commerce sales and app installs",
      "Creatives, UGC videos and copy made in-house",
      "Meta Pixel + Conversions API for accurate results",
    ],
    formTitle: "Get a free Facebook ads audit",
    whyTitle: "What a top Facebook ads agency does differently",
    whyIntro:
      "Meta’s algorithm rewards strong creative and clean conversion data. The best Facebook ads agencies spend as much time on those two things as on targeting.",
    why: [
      ["Creative is the targeting", "We produce a steady pipeline of static, carousel, video and UGC ads, and test hooks and angles every week to find winners before fatigue sets in."],
      ["Conversions API set up right", "Server-side events with proper deduplication and event match quality, so Meta optimizes on real leads and purchases despite iOS and cookie limits."],
      ["Full-funnel structure", "Prospecting, engagement and retargeting audiences that move people from first view to enquiry or checkout."],
      ["Lead quality, not just volume", "Qualifying questions, instant forms or landing pages, and CRM feedback so cheap leads don’t become wasted sales calls."],
      ["Advantage+ when it fits", "We use Advantage+ shopping and audience tools where they outperform manual setups — and keep control where they don’t."],
      ["Clear reporting", "Cost per lead, cost per purchase, ROAS and creative performance in plain language every week."],
    ],
    includedTitle: "Facebook and Instagram ads management services",
    included: [
      "Ad account and Pixel audit",
      "Audience research and campaign strategy",
      "Static, carousel, video and UGC ad creatives",
      "Ad copy and hook testing",
      "Meta Pixel, Conversions API and event setup",
      "Lead forms, landing pages and CRM integration",
      "Retargeting and lookalike audiences",
      "Weekly optimization and monthly reports",
    ],
    steps: [
      ["Audit & strategy", "We review your account, Pixel, creatives and offers, then map a full-funnel plan."],
      ["Creative & tracking", "We produce the first round of creatives and set up Conversions API so results are measured correctly."],
      ["Test, learn, scale", "Weekly creative testing and budget shifts toward the ads, audiences and offers that convert."],
    ],
    faqs: [
      ["How do I find the best Facebook ads agency?", "Ask to see real results in your industry, how they produce new creatives each month, and whether they set up the Conversions API. A good agency reports on cost per lead or sale, not reach and likes."],
      ["Do you also run Instagram ads?", "Yes. Facebook and Instagram ads run from the same Meta Ads Manager, and we create placements and formats for Feed, Stories and Reels."],
      ["How much budget do Facebook ads need?", "For lead generation, many businesses start around $30–$100 a day so campaigns can exit the learning phase. E-commerce often needs more. We recommend a budget after the audit."],
      ["Do you make the ad creatives?", "Yes. Our creative studio and UGC creators make images, videos and copy, so you don’t need a separate design team."],
      ["Can agencies resell your Facebook ads management?", "Yes. We work as a white label Facebook ads partner, fully under your agency’s brand, with an NDA."],
    ],
  },
  {
    slug: "conversion-tracking",
    navLabel: "Conversion Tracking",
    metaTitle: "Conversion Tracking Solutions — GA4, GTM, Meta CAPI & Server-Side Tracking",
    metaDescription:
      "Conversion tracking solutions that fix broken data: GA4, Google Tag Manager, Google Ads enhanced conversions, Meta Conversions API, server-side tracking and offline conversion imports from your CRM.",
    keywords: ["conversion tracking solutions", "conversion tracking agency", "server-side tracking", "Meta Conversions API setup", "Google Ads conversion tracking"],
    serviceType: "Conversion tracking setup",
    eyebrow: "Conversion tracking solutions",
    h1: ["Conversion tracking you can ", "finally trust."],
    lead:
      "If your ad platforms, analytics and CRM all show different numbers, your budget is being optimized on guesswork. We set up accurate conversion tracking across Google, Meta, LinkedIn and your CRM — client-side and server-side.",
    checks: [
      "GA4, Google Tag Manager & server-side GTM",
      "Google Ads enhanced conversions & offline imports",
      "Meta Conversions API with proper deduplication",
    ],
    formTitle: "Get a free tracking audit",
    whyTitle: "Why conversion tracking decides your ad results",
    whyIntro:
      "Google’s Smart Bidding and Meta’s algorithm learn from the conversions you send them. Missing or duplicated conversions mean the platforms optimize for the wrong people. Our co-founder has raised attribution accuracy from 60% to 95% with server-side tracking and CAPI.",
    why: [
      ["Recover lost conversions", "Ad blockers, iOS privacy and cookie limits hide a large share of conversions. Server-side tracking and CAPI bring much of that data back."],
      ["One source of truth", "We align GA4, ad platforms and your CRM so leads, sales and revenue match across reports."],
      ["Smarter bidding", "Clean conversion values and offline imports let Target CPA and ROAS bidding optimize for real customers, not form spam."],
      ["Lead-to-sale visibility", "Pass CRM stages (qualified, booked, won) back to Google and Meta so you see which ads create revenue."],
      ["Privacy-aware setup", "Consent mode, first-party data and careful handling of personal data, so tracking stays compliant."],
      ["Documented and owned by you", "Every tag, trigger and event is documented. You keep full ownership of your containers and accounts."],
    ],
    includedTitle: "Our conversion tracking services",
    included: [
      "Tracking audit across all platforms",
      "Google Tag Manager (web and server-side) setup",
      "GA4 events, conversions and e-commerce tracking",
      "Google Ads conversions and enhanced conversions",
      "Meta Pixel and Conversions API (CAPI)",
      "LinkedIn Insight Tag and conversions",
      "Call tracking and form tracking",
      "Offline conversion imports from HubSpot, GoHighLevel and other CRMs",
    ],
    steps: [
      ["Audit", "We test every conversion on your site and compare platform numbers to find what’s missing or double-counted."],
      ["Implement", "We rebuild tracking in Google Tag Manager, add server-side events and connect your CRM."],
      ["Verify & document", "We test end to end, hand over documentation and keep monitoring for breaks."],
    ],
    faqs: [
      ["What is server-side tracking?", "Server-side tracking sends conversion events from a server you control instead of only from the visitor’s browser. It is less affected by ad blockers and browser privacy limits, so more conversions reach Google and Meta."],
      ["What is the Meta Conversions API (CAPI)?", "CAPI sends website and offline events directly from your server to Meta. Used together with the Pixel and proper deduplication, it improves match quality and campaign optimization."],
      ["Do I need conversion tracking if I already have Google Analytics?", "Yes. GA4 alone doesn’t send optimized conversion data to Google Ads, Meta or LinkedIn. Each ad platform needs its own correctly configured conversions."],
      ["Can you track phone calls and offline sales?", "Yes. We set up call tracking and import offline conversions from your CRM so the ad platforms learn which clicks became customers."],
      ["Which tools and CRMs do you work with?", "Google Tag Manager, GA4, Google Ads, Meta, LinkedIn, Stape, Shopify, WooCommerce, HubSpot, GoHighLevel and most CRMs that support webhooks or exports."],
    ],
  },
  {
    slug: "web-analytics-agency",
    navLabel: "Web Analytics",
    metaTitle: "Web Analytics Agency — GA4, Google Tag Manager & Looker Studio Dashboards",
    metaDescription:
      "A web analytics agency that turns data into decisions: GA4 setup and audits, Google Tag Manager, event tracking, attribution and Looker Studio dashboards your team will actually use.",
    keywords: ["web analytics agency", "GA4 agency", "Google Analytics consultant", "Looker Studio dashboards", "marketing analytics agency"],
    serviceType: "Web analytics",
    eyebrow: "Web analytics agency",
    h1: ["Web analytics that answers ", "“what’s working?”"],
    lead:
      "We set up and audit Google Analytics 4, Google Tag Manager and marketing dashboards, so you can see which channels, campaigns and pages bring customers — and where visitors drop off.",
    checks: [
      "GA4 setup, audits and migration clean-up",
      "Event tracking and e-commerce reporting",
      "Looker Studio dashboards with your branding",
    ],
    formTitle: "Get a free analytics audit",
    whyTitle: "What you get from a web analytics agency",
    whyIntro:
      "Most GA4 properties are collecting data nobody trusts. We fix the setup, define the events that matter to your business, and build reports people actually read.",
    why: [
      ["Clean GA4 setup", "Correct data streams, filters, cross-domain tracking, consent mode and key events — configured for your business, not left on defaults."],
      ["Events that match your funnel", "Form starts, submissions, calls, bookings, add-to-cart and purchases tracked as clear, named events."],
      ["Attribution you understand", "Channel and campaign reporting with UTM standards, so paid, organic, social and email are compared fairly."],
      ["Dashboards, not data dumps", "Looker Studio dashboards that combine GA4, Google Ads, Meta and CRM data into one view — branded for you or your clients."],
      ["Conversion rate insights", "Funnel and page analysis that shows where visitors leave, feeding landing page and CRO improvements."],
      ["Training and handover", "We walk your team through the reports and document everything so you aren’t dependent on us."],
    ],
    includedTitle: "Web analytics services",
    included: [
      "GA4 audit and setup",
      "Google Tag Manager implementation",
      "Event, conversion and e-commerce tracking",
      "UTM and campaign naming standards",
      "Cross-domain and subdomain tracking",
      "Consent mode configuration",
      "Looker Studio and AgencyAnalytics dashboards",
      "Monthly insight reports and recommendations",
    ],
    steps: [
      ["Audit", "We check your GA4 property, tags and reports and list what’s missing, broken or misleading."],
      ["Fix & build", "We implement the tracking plan in GTM and GA4, then build your dashboards."],
      ["Report & improve", "Regular insight reports with clear recommendations for ads, pages and budget."],
    ],
    faqs: [
      ["What does a web analytics agency do?", "A web analytics agency sets up and maintains tools like GA4 and Google Tag Manager, makes sure the data is accurate, and turns it into reports and recommendations that improve marketing results."],
      ["Can you audit our existing GA4 setup?", "Yes. Our free audit checks data streams, events, conversions, filters, consent mode and reporting, and gives you a prioritized list of fixes."],
      ["Do you build Looker Studio dashboards?", "Yes. We build Looker Studio dashboards that combine GA4, ad platforms and CRM data, with your branding or your agency’s branding."],
      ["Is web analytics different from conversion tracking?", "They overlap. Conversion tracking makes sure ad platforms receive the right conversions. Web analytics covers the full picture of your site and marketing performance. We do both."],
      ["Do you work white label for agencies?", "Yes. Agencies use us to set up analytics and dashboards for their clients under the agency’s brand."],
    ],
  },
  {
    slug: "digital-marketing-agency-bangladesh",
    navLabel: "Agency in Bangladesh",
    metaTitle: "Digital Marketing & Advertising Agency in Bangladesh",
    metaDescription:
      "MindandMatrix Co. is a digital marketing and advertising agency in Dhaka, Bangladesh. Google Ads, Facebook ads, creatives, conversion tracking and lead generation for Bangladeshi brands and international agencies.",
    keywords: [
      "digital marketing agency in Bangladesh",
      "advertising agency in Bangladesh",
      "top Bangladeshi advertising agency",
      "best digital marketing agency in Bangladesh",
      "best ad agency in Bangladesh",
      "Facebook ads agency Bangladesh",
      "Google Ads agency Bangladesh",
    ],
    serviceType: "Digital marketing and advertising",
    eyebrow: "Digital marketing agency in Bangladesh",
    h1: ["A Bangladeshi advertising agency ", "built for growth."],
    lead:
      "From Dhaka, our team runs performance marketing for Bangladeshi brands and for agencies in the US, UK, Canada and Australia. Google Ads, Facebook and Instagram ads, creatives, landing pages and tracking — all under one roof.",
    checks: [
      "Google Ads, Facebook, Instagram, YouTube & LinkedIn ads",
      "Creative studio, UGC creators and landing pages",
      "Lead generation for finance, real estate, healthcare & more",
    ],
    formTitle: "Talk to our Dhaka team",
    whyTitle: "Why brands choose us as their advertising agency in Bangladesh",
    whyIntro:
      "Brands looking for the best digital marketing agency in Bangladesh want proof, not promises. Our team has generated 89,537 leads for Aamartaka, feeding 250M+ BDT in loan disbursement, and our co-founder has led campaigns for brands like ASUS and Yamaha.",
    why: [
      ["Proven local results", "Lead generation and performance campaigns for Bangladeshi brands in finance, retail, e-commerce and services — with numbers we can show."],
      ["International standards", "The same processes we use for agencies in the US, UK and Australia: tracking first, weekly optimization and clear reporting."],
      ["Bangla and English creative", "Ad copy, creatives and landing pages in Bangla and English that speak to your audience."],
      ["Facebook-first expertise", "Facebook and Instagram are where Bangladeshi customers spend their time. We build full-funnel Meta campaigns that convert, not just reach."],
      ["Google Ads and YouTube", "Search, YouTube and Performance Max campaigns to capture demand when people are ready to buy."],
      ["Accurate tracking", "Pixel, Conversions API, GA4 and CRM integration, so you know your real cost per lead and cost per sale."],
    ],
    includedTitle: "Our digital marketing services in Bangladesh",
    included: [
      "Facebook and Instagram advertising",
      "Google Ads, YouTube and Performance Max",
      "Social media management and content calendars",
      "Ad creatives, video and UGC content",
      "Landing pages and website funnels",
      "Conversion tracking and web analytics",
      "Lead generation and CRM automation",
      "White label services for international agencies",
    ],
    steps: [
      ["Discovery call", "We learn your business, goals and budget, and review what you’ve already tried."],
      ["Plan & launch", "A channel plan, creatives and tracking, then campaign launch — usually within 1–2 weeks."],
      ["Grow", "Weekly optimization and monthly reviews focused on leads, sales and ROAS."],
    ],
    faqs: [
      ["Which is the best digital marketing agency in Bangladesh?", "The best agency for you is one that shows real results, sets up accurate tracking and reports on leads and sales. We share our case studies — like 89,537 leads for Aamartaka — and start every project with a free audit so you can judge our work first."],
      ["Where is MindandMatrix Co. located?", "Our team is based in Dhaka, Bangladesh, and we work with clients across Bangladesh and internationally."],
      ["Do you run Facebook ads for Bangladeshi businesses?", "Yes. Facebook and Instagram ads are a core service, including creatives, lead forms, Messenger campaigns and Conversions API tracking."],
      ["Do you work with international agencies?", "Yes. Agencies in the US, UK, Canada and Australia use us as their white label paid media team, with working hours that overlap their time zones."],
      ["How do I get started?", "Send the form on this page or message us on WhatsApp. We reply within one business day and start with a free audit."],
    ],
  },
];

export const getServicePage = (slug) => SERVICE_PAGES.find((p) => p.slug === slug) || null;
